# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image:
  repository: lrochette/worker
  tag: latest
  #pullSecret: cfcr

postgresql:
  postgresUser: postgres
  postgresPassword: postgres

redis:
  usePassword: false

replicaCount: 1
