# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
cpu_limit: 100m
imagePullPolicy: IfNotPresent
mem_limit: 256Mi
mem_request: 64Mi

replicaCount: 1
