version: "2"
services:
  voting-app:
    build: ./voting-app/.
    volumes:
      - ./voting-app:/app
    ports:
      - "5000:80"
    links:
      - redis

  redis:
    image: redis
    ports: ["6379"]

  worker:
    build: ./worker
    links:
      - db
      - redis

  db:
    image: postgres:9.4
    volumes:
      - "myvolume:/var/lib/postgresql/data"

  result-app:
    build: ./result-app/.
    volumes:
      - ./result-app:/app
    ports:
      - "5001:80"
    links:
      - db
volumes:
  myvolume:
