version: "3.2"

services:
  vote:
    image: dockersamples/examplevotingapp_vote:dotnet-nanoserver-1809
    build: 
      context: ./vote/dotnet
      dockerfile: Dockerfile.1809
    ports:
      - "5000:80"
    depends_on:
      - message-queue

  result:
    image: dockersamples/examplevotingapp_result:dotnet-nanoserver-1809
    build: 
      context: ./result/dotnet
      dockerfile: Dockerfile.1809
    ports:
      - "5001:80"
    environment:      
      - "ConnectionStrings:ResultData=Server=db;Port=4000;Database=votes;User=root;SslMode=None"
    depends_on:
      - db

  worker:
    image: dockersamples/examplevotingapp_worker:dotnet-nanoserver-1809
    build:
      context: ./worker/dotnet
      dockerfile: Dockerfile.1809
    environment:      
      - "ConnectionStrings:VoteData=Server=db;Port=4000;Database=votes;User=root;SslMode=None"
    depends_on:
      - message-queue
      - db

  message-queue:
    image: dockersamples/nats:nanoserver-1809

  db:
    image: dockersamples/tidb:nanoserver-1809
    ports:
      - "3306:4000"

networks:
  default:
    external:
      name: nat