dependencies:
- name: postgresql
  version: 0.9.5
  repository: https://kubernetes-charts.storage.googleapis.com/ 
  condition: postgres.enabled
  tags:
  - db
- name: redis
  version: 1.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: redis.enabled
  tags:
  - queue
- name: result
  version: 0.1.0
  repository: file://local-charts/result
  tags:
  - node
- name: vote
  version: 0.1.0
  repository: file://local-charts/vote
  tags:
  - python
- name: worker
  version: 0.1.0
  repository: file://local-charts/worker
  tags:
  - dotnet