platform:
  profile: run
  
  additional_packages:
    - dapr
    - gitops-configurer
    - rabbitmq-operator
  
  excluded_packages:
    - metrics-server
  
  ingress:
    domain: cloud.thomasvitale.dev
    issuer:
      type: letsencrypt
      email: security@kadras.io

contour:
  certificates:
    useCertManager: true

flux:
  optional_components:
    helm_controller: true

gitops_configurer:
  type: flux-kustomization
  git:
    url: https://github.com/salaboy/example-voting-app
    path: platform/gitops/clusters/cloud
