name: build and push to dockerhub

on:
  push:
    branches:
      - master

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: build, tag and push vote image
        id: vote
        env:
          DOCKER_REGISTRY: georgerodriguex
          DOCKER_REPOSITORY: vote
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG ./vote/
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest"
      -
        name: build, tag and push vote worker
        id: worker
        env:
          DOCKER_REGISTRY: georgerodriguex
          DOCKER_REPOSITORY: worker
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG ./worker/
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest"
      -
        name: build, tag and push result image
        id: result
        env:
          DOCKER_REGISTRY: georgerodriguex
          DOCKER_REPOSITORY: result
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG ./result/
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG
          docker tag $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest
          echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_REPOSITORY:latest"
      - 
        name: ssh deploy aws
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker-compose down
            docker pull georgerodriguex/vote:latest
            docker pull georgerodriguex/worker:latest
            docker pull georgerodriguex/result:latest
            docker-compose up -d
      
      - 
        name: ssh deploy gcp
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST2 }}
          username: ${{ secrets.USERNAME2 }}
          key: ${{ secrets.KEY2 }}
          port: ${{ secrets.PORT }}
          script: |
            docker-compose down
            docker pull georgerodriguex/vote:latest
            docker pull georgerodriguex/worker:latest
            docker pull georgerodriguex/result:latest
            docker-compose up -d