name: push to ghcr
on:
  push:
    branches: ci

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to GitHub Package Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GHCR_TOKEN }}
        -
          name: build, tag and push vote image
          id: vote
          env:
            DOCKER_REGISTRY: ghcr.io
            DOCKER_USER: georgerodriguex
            DOCKER_REPOSITORY: vote
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG ./vote/
            docker push $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG
            docker tag $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest
            docker push $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest
            echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest"
        -
          name: build, tag and push vote worker
          id: worker
          env:
            DOCKER_REGISTRY: ghcr.io
            DOCKER_USER: georgerodriguex
            DOCKER_REPOSITORY: worker
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG ./worker/
            docker push $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG
            docker tag $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest
            docker push $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest
            echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest"
        -
          name: build, tag and push result image
          id: result
          env:
            DOCKER_REGISTRY: ghcr.io
            DOCKER_USER: georgerodriguex
            DOCKER_REPOSITORY: result
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG ./result/
            docker push $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG
            docker tag $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest
            docker push $DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest
            echo "::set-output name=image::$DOCKER_REGISTRY/$DOCKER_USER/$DOCKER_REPOSITORY:latest"