#some Env variables
env:
    IMAGE_NAME: "app"
    DOCKERFILE_CONTEXT: "vote/"
  
name: S1-tests

on: 
  pull_request:
    paths:
    - 'vote/**Dockerfile' #conditions to scan only when modifying the DOCKERFILE related to image

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/s1cnscli:latest
      options: --entrypoint ""
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set Tags #New env varaibles to add tag based on date & hour for the new image
      run: echo "IMAGE_TAG=vote-$(date +%Y%m%d%H%M)" >> $GITHUB_ENV 
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and save
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.DOCKERFILE_CONTEXT }}
        tags: ${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        load: true

    - name: Configure SentinelOne CNS CLI
      run: s1-cns-cli config --api-token $TOKEN --endpoint-url https://app.pingsafe.com
      env:
        TOKEN: ${{secrets.SENTINELONE_CNS_TOKEN}}

    - name: Configure git config
      run: git config --global --add safe.directory $PWD

    - name: Run S1 Vulm
      run:  s1-cns-cli scan vuln -d docker.io/${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
    
    - name: Login to the registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push
      uses: docker/build-push-action@v3
      with:
        context: ${{ env.DOCKERFILE_CONTEXT }}
        push: true
        tags: ${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
