name: SentinelOne CNS Scan

on:
  # Triggers the workflow when pull_request created on master/main branch
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master, main ]

jobs:
  s1-cns-cli:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/s1cnscli:latest
      options: --entrypoint ""

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configure SentinelOne CNS CLI
        run: s1-cns-cli config --api-token $TOKEN --endpoint-url https://app.pingsafe.com
        env:
         TOKEN: ${{secrets.SENTINELONE_CNS_TOKEN}}

      - name: Configure git config
        run: git config --global --add safe.directory $PWD

      - name: Run IAC
        run:  s1-cns-cli scan vuln -d $PWD
        env:
          DEST: ${{ github.event.pull_request.base.sha }}
          SRC: ${{ github.event.pull_request.head.ref }}

    
