name: CI S3 reusable repo

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #branches:
  #  - master

  #pull_request:
  #  branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  VERSION: 'latest'

jobs:
  call-reusable-workflow:
    name: Graasp test
    uses: victorggonzalez/workflows/.github/workflows/s3-cintegration.yml@main
    with:
      build-folder: 'result/build'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME }}
      app-id: ${{ secrets.APP_ID }}
      graasp-domain-dev: ${{ secrets.GRAASP_DOMAIN_DEV }}
      cloudfront-distribution: ${{ secrets.DEV_CLOUDFRONT_DISTRIBUTION }}

